"""Phase 4 Volunteer and Service Requests

Revision ID: 22583a80dde2
Revises: ff6398754a6b
Create Date: 2026-08-13 22:19:09.944979

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22583a80dde2'
down_revision: Union[str, Sequence[str], None] = 'ff6398754a6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
