"""Phase 2 Models

Revision ID: 54c3f1141a46
Revises: 9e73dfd5b304
Create Date: 2026-08-13 21:31:55.751987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54c3f1141a46'
down_revision: Union[str, Sequence[str], None] = '9e73dfd5b304'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_profiles', sa.Column('bloodGroup', sa.String(length=10), nullable=True))
    op.add_column('patient_profiles', sa.Column('allergies', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('medicalConditions', sa.JSON(), nullable=True))
    op.add_column('patient_profiles', sa.Column('currentMedications', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_profiles', 'currentMedications')
    op.drop_column('patient_profiles', 'medicalConditions')
    op.drop_column('patient_profiles', 'allergies')
    op.drop_column('patient_profiles', 'bloodGroup')
    # ### end Alembic commands ###
